language: java

jdk: oraclejdk8

env:
  global: ORG_GRADLE_PROJECT_downloadIdeaSources=false
  matrix:
    - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
    - ORG_GRADLE_PROJECT_ideaVersion=2017.3.3
    - ORG_GRADLE_PROJECT_ideaVersion=2017.2.6

matrix:
  allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
  fast_finish: true

install: true

script:
  # BACKCOMPAT:
  # HACK: Force grammar kit to use current IDEA version when generating parser.
  # For actual compilation and running the version from the matrix will be used.
  - ORG_GRADLE_PROJECT_ideaVersion=2017.3.3 ./gradlew generateFusionParser
  - ./gradlew check -x generateFusionParser

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/